In [75]:
import pandas as pd
import random

In [76]:
df=pd.read_csv('ratings.csv')
df

          id  Ratings  Reviews   Rank
0      10000        5     3717  18585
1      10001        3     2085   6255
2      10002        2     2522   5044
3      10003        4     4688  18752
4      10004        2     2506   5012
...      ...      ...      ...    ...
44441   9995        1     1895   1895
44442   9996        4     3051  12204
44443   9997        5       57    285
44444   9998        3     1906   5718
44445   9999        1      336    336

[44446 rows x 4 columns]

In [77]:
transactions_list=[]
for i in range(100000):
    transactions_list.append(i+200000)
transactions_list

[200000,
 200001,
 200002,
 200003,
 200004,
 200005,
 200006,
 200007,
 200008,
 200009,
 200010,
 200011,
 200012,
 200013,
 200014,
 200015,
 200016,
 200017,
 200018,
 200019,
 200020,
 200021,
 200022,
 200023,
 200024,
 200025,
 200026,
 200027,
 200028,
 200029,
 200030,
 200031,
 200032,
 200033,
 200034,
 200035,
 200036,
 200037,
 200038,
 200039,
 200040,
 200041,
 200042,
 200043,
 200044,
 200045,
 200046,
 200047,
 200048,
 200049,
 200050,
 200051,
 200052,
 200053,
 200054,
 200055,
 200056,
 200057,
 200058,
 200059,
 200060,
 200061,
 200062,
 200063,
 200064,
 200065,
 200066,
 200067,
 200068,
 200069,
 200070,
 200071,
 200072,
 200073,
 200074,
 200075,
 200076,
 200077,
 200078,
 200079,
 200080,
 200081,
 200082,
 200083,
 200084,
 200085,
 200086,
 200087,
 200088,
 200089,
 200090,
 200091,
 200092,
 200093,
 200094,
 200095,
 200096,
 200097,
 200098,
 200099,
 200100,
 200101,
 200102,
 200103,
 200104,
 200105,
 200106,
 200107,
 200108,
 200109,
 200110,
 200111,
 200112,
 200113,
 200114,
 200115,
 200116,
 200117,
 200118,
 200119,
 200120,
 200121,
 200122,
 200123,
 200124,
 200125,
 200126,
 200127,
 200128,
 200129,
 200130,
 200131,
 200132,
 200133,
 200134,
 200135,
 200136,
 200137,
 200138,
 200139,
 200140,
 200141,
 200142,
 200143,
 200144,
 200145,
 200146,
 200147,
 200148,
 200149,
 200150,
 200151,
 200152,
 200153,
 200154,
 200155,
 200156,
 200157,
 200158,
 200159,
 200160,
 200161,
 200162,
 200163,
 200164,
 200165,
 200166,
 200167,
 200168,
 200169,
 200170,
 200171,
 200172,
 200173,
 200174,
 200175,
 200176,
 200177,
 200178,
 200179,
 200180,
 200181,
 200182,
 200183,
 200184,
 200185,
 200186,
 200187,
 200188,
 200189,
 200190,
 200191,
 200192,
 200193,
 200194,
 200195,
 200196,
 200197,
 200198,
 200199,
 200200,
 200201,
 200202,
 200203,
 200204,
 200205,
 200206,
 200207,
 200208,
 200209,
 200210,
 200211,
 200212,
 200213,
 200214,
 200215,
 200216,
 200217,
 200218,
 200219,
 200220,
 200221,
 200222,
 200223,
 200224,
 200225,
 200226,
 200227,
 200228,
 200229,
 200230,
 200231,
 200232,
 200233,
 200234,
 200235,
 200236,
 200237,
 200238,
 200239,
 200240,
 200241,
 200242,
 200243,
 200244,
 200245,
 200246,
 200247,
 200248,
 200249,
 200250,
 200251,
 200252,
 200253,
 200254,
 200255,
 200256,
 200257,
 200258,
 200259,
 200260,
 200261,
 200262,
 200263,
 200264,
 200265,
 200266,
 200267,
 200268,
 200269,
 200270,
 200271,
 200272,
 200273,
 200274,
 200275,
 200276,
 200277,
 200278,
 200279,
 200280,
 200281,
 200282,
 200283,
 200284,
 200285,
 200286,
 200287,
 200288,
 200289,
 200290,
 200291,
 200292,
 200293,
 200294,
 200295,
 200296,
 200297,
 200298,
 200299,
 200300,
 200301,
 200302,
 200303,
 200304,
 200305,
 200306,
 200307,
 200308,
 200309,
 200310,
 200311,
 200312,
 200313,
 200314,
 200315,
 200316,
 200317,
 200318,
 200319,
 200320,
 200321,
 200322,
 200323,
 200324,
 200325,
 200326,
 200327,
 200328,
 200329,
 200330,
 200331,
 200332,
 200333,
 200334,
 200335,
 200336,
 200337,
 200338,
 200339,
 200340,
 200341,
 200342,
 200343,
 200344,
 200345,
 200346,
 200347,
 200348,
 200349,
 200350,
 200351,
 200352,
 200353,
 200354,
 200355,
 200356,
 200357,
 200358,
 200359,
 200360,
 200361,
 200362,
 200363,
 200364,
 200365,
 200366,
 200367,
 200368,
 200369,
 200370,
 200371,
 200372,
 200373,
 200374,
 200375,
 200376,
 200377,
 200378,
 200379,
 200380,
 200381,
 200382,
 200383,
 200384,
 200385,
 200386,
 200387,
 200388,
 200389,
 200390,
 200391,
 200392,
 200393,
 200394,
 200395,
 200396,
 200397,
 200398,
 200399,
 200400,
 200401,
 200402,
 200403,
 200404,
 200405,
 200406,
 200407,
 200408,
 200409,
 200410,
 200411,
 200412,
 200413,
 200414,
 200415,
 200416,
 200417,
 200418,
 200419,
 200420,
 200421,
 200422,
 200423,
 200424,
 200425,
 200426,
 200427,
 200428,
 200429,
 200430,
 200431,
 200432,
 200433,
 200434,
 200435,
 200436,
 200437,
 200438,
 200439,
 200440,
 200441,
 200442,
 200443,
 200444,
 200445,
 200446,
 200447,
 200448,
 200449,
 200450,
 200451,
 200452,
 200453,
 200454,
 200455,
 200456,
 200457,
 200458,
 200459,
 200460,
 200461,
 200462,
 200463,
 200464,
 200465,
 200466,
 200467,
 200468,
 200469,
 200470,
 200471,
 200472,
 200473,
 200474,
 200475,
 200476,
 200477,
 200478,
 200479,
 200480,
 200481,
 200482,
 200483,
 200484,
 200485,
 200486,
 200487,
 200488,
 200489,
 200490,
 200491,
 200492,
 200493,
 200494,
 200495,
 200496,
 200497,
 200498,
 200499,
 200500,
 200501,
 200502,
 200503,
 200504,
 200505,
 200506,
 200507,
 200508,
 200509,
 200510,
 200511,
 200512,
 200513,
 200514,
 200515,
 200516,
 200517,
 200518,
 200519,
 200520,
 200521,
 200522,
 200523,
 200524,
 200525,
 200526,
 200527,
 200528,
 200529,
 200530,
 200531,
 200532,
 200533,
 200534,
 200535,
 200536,
 200537,
 200538,
 200539,
 200540,
 200541,
 200542,
 200543,
 200544,
 200545,
 200546,
 200547,
 200548,
 200549,
 200550,
 200551,
 200552,
 200553,
 200554,
 200555,
 200556,
 200557,
 200558,
 200559,
 200560,
 200561,
 200562,
 200563,
 200564,
 200565,
 200566,
 200567,
 200568,
 200569,
 200570,
 200571,
 200572,
 200573,
 200574,
 200575,
 200576,
 200577,
 200578,
 200579,
 200580,
 200581,
 200582,
 200583,
 200584,
 200585,
 200586,
 200587,
 200588,
 200589,
 200590,
 200591,
 200592,
 200593,
 200594,
 200595,
 200596,
 200597,
 200598,
 200599,
 200600,
 200601,
 200602,
 200603,
 200604,
 200605,
 200606,
 200607,
 200608,
 200609,
 200610,
 200611,
 200612,
 200613,
 200614,
 200615,
 200616,
 200617,
 200618,
 200619,
 200620,
 200621,
 200622,
 200623,
 200624,
 200625,
 200626,
 200627,
 200628,
 200629,
 200630,
 200631,
 200632,
 200633,
 200634,
 200635,
 200636,
 200637,
 200638,
 200639,
 200640,
 200641,
 200642,
 200643,
 200644,
 200645,
 200646,
 200647,
 200648,
 200649,
 200650,
 200651,
 200652,
 200653,
 200654,
 200655,
 200656,
 200657,
 200658,
 200659,
 200660,
 200661,
 200662,
 200663,
 200664,
 200665,
 200666,
 200667,
 200668,
 200669,
 200670,
 200671,
 200672,
 200673,
 200674,
 200675,
 200676,
 200677,
 200678,
 200679,
 200680,
 200681,
 200682,
 200683,
 200684,
 200685,
 200686,
 200687,
 200688,
 200689,
 200690,
 200691,
 200692,
 200693,
 200694,
 200695,
 200696,
 200697,
 200698,
 200699,
 200700,
 200701,
 200702,
 200703,
 200704,
 200705,
 200706,
 200707,
 200708,
 200709,
 200710,
 200711,
 200712,
 200713,
 200714,
 200715,
 200716,
 200717,
 200718,
 200719,
 200720,
 200721,
 200722,
 200723,
 200724,
 200725,
 200726,
 200727,
 200728,
 200729,
 200730,
 200731,
 200732,
 200733,
 200734,
 200735,
 200736,
 200737,
 200738,
 200739,
 200740,
 200741,
 200742,
 200743,
 200744,
 200745,
 200746,
 200747,
 200748,
 200749,
 200750,
 200751,
 200752,
 200753,
 200754,
 200755,
 200756,
 200757,
 200758,
 200759,
 200760,
 200761,
 200762,
 200763,
 200764,
 200765,
 200766,
 200767,
 200768,
 200769,
 200770,
 200771,
 200772,
 200773,
 200774,
 200775,
 200776,
 200777,
 200778,
 200779,
 200780,
 200781,
 200782,
 200783,
 200784,
 200785,
 200786,
 200787,
 200788,
 200789,
 200790,
 200791,
 200792,
 200793,
 200794,
 200795,
 200796,
 200797,
 200798,
 200799,
 200800,
 200801,
 200802,
 200803,
 200804,
 200805,
 200806,
 200807,
 200808,
 200809,
 200810,
 200811,
 200812,
 200813,
 200814,
 200815,
 200816,
 200817,
 200818,
 200819,
 200820,
 200821,
 200822,
 200823,
 200824,
 200825,
 200826,
 200827,
 200828,
 200829,
 200830,
 200831,
 200832,
 200833,
 200834,
 200835,
 200836,
 200837,
 200838,
 200839,
 200840,
 200841,
 200842,
 200843,
 200844,
 200845,
 200846,
 200847,
 200848,
 200849,
 200850,
 200851,
 200852,
 200853,
 200854,
 200855,
 200856,
 200857,
 200858,
 200859,
 200860,
 200861,
 200862,
 200863,
 200864,
 200865,
 200866,
 200867,
 200868,
 200869,
 200870,
 200871,
 200872,
 200873,
 200874,
 200875,
 200876,
 200877,
 200878,
 200879,
 200880,
 200881,
 200882,
 200883,
 200884,
 200885,
 200886,
 200887,
 200888,
 200889,
 200890,
 200891,
 200892,
 200893,
 200894,
 200895,
 200896,
 200897,
 200898,
 200899,
 200900,
 200901,
 200902,
 200903,
 200904,
 200905,
 200906,
 200907,
 200908,
 200909,
 200910,
 200911,
 200912,
 200913,
 200914,
 200915,
 200916,
 200917,
 200918,
 200919,
 200920,
 200921,
 200922,
 200923,
 200924,
 200925,
 200926,
 200927,
 200928,
 200929,
 200930,
 200931,
 200932,
 200933,
 200934,
 200935,
 200936,
 200937,
 200938,
 200939,
 200940,
 200941,
 200942,
 200943,
 200944,
 200945,
 200946,
 200947,
 200948,
 200949,
 200950,
 200951,
 200952,
 200953,
 200954,
 200955,
 200956,
 200957,
 200958,
 200959,
 200960,
 200961,
 200962,
 200963,
 200964,
 200965,
 200966,
 200967,
 200968,
 200969,
 200970,
 200971,
 200972,
 200973,
 200974,
 200975,
 200976,
 200977,
 200978,
 200979,
 200980,
 200981,
 200982,
 200983,
 200984,
 200985,
 200986,
 200987,
 200988,
 200989,
 200990,
 200991,
 200992,
 200993,
 200994,
 200995,
 200996,
 200997,
 200998,
 200999,
 ...]

In [78]:
product_id=list(df['id'])
product_id

[10000,
 10001,
 10002,
 10003,
 10004,
 10005,
 10006,
 10007,
 10008,
 10009,
 10010,
 10011,
 10012,
 10013,
 10014,
 10015,
 10016,
 10017,
 10018,
 10019,
 10020,
 10021,
 10022,
 10023,
 10024,
 10025,
 10026,
 10027,
 10028,
 10029,
 10030,
 10031,
 10032,
 10033,
 10034,
 10035,
 10037,
 10039,
 10040,
 10041,
 10042,
 10043,
 10044,
 10045,
 10046,
 10047,
 10048,
 10049,
 10050,
 10051,
 10052,
 10053,
 10054,
 10056,
 10057,
 10058,
 10059,
 10060,
 10061,
 10062,
 10063,
 10064,
 10065,
 10066,
 10067,
 10068,
 10069,
 10070,
 10071,
 10072,
 10073,
 10074,
 10075,
 10076,
 10078,
 10079,
 10080,
 10081,
 10082,
 10083,
 10088,
 10089,
 10092,
 10093,
 10095,
 10096,
 10097,
 10098,
 10099,
 10101,
 10102,
 10104,
 10105,
 10106,
 10107,
 10108,
 10109,
 10110,
 10111,
 10112,
 10113,
 10114,
 10115,
 10117,
 10122,
 10125,
 10126,
 10127,
 10128,
 10129,
 10130,
 10131,
 10133,
 10134,
 10135,
 10136,
 10137,
 10138,
 10139,
 10140,
 10141,
 10142,
 10143,
 10144,
 10145,
 10146,
 10147,
 10148,
 10149,
 10150,
 10151,
 10152,
 10153,
 10154,
 10155,
 10156,
 10157,
 10158,
 10159,
 10160,
 10161,
 10162,
 10164,
 10166,
 10167,
 10168,
 10169,
 10170,
 10171,
 10172,
 10173,
 10174,
 10175,
 10176,
 10177,
 10178,
 10179,
 10180,
 10181,
 10182,
 10183,
 10184,
 10185,
 10186,
 10187,
 10188,
 10189,
 10190,
 10192,
 10193,
 10194,
 10195,
 10196,
 10197,
 10198,
 10199,
 10200,
 10202,
 10203,
 10204,
 10205,
 10207,
 10208,
 10209,
 10210,
 10211,
 10213,
 10214,
 10215,
 10216,
 10217,
 10219,
 10220,
 10221,
 10222,
 10223,
 10224,
 10225,
 10226,
 10227,
 10228,
 10229,
 10230,
 10231,
 10235,
 10236,
 10237,
 10238,
 10239,
 10240,
 10241,
 10242,
 10243,
 10244,
 10245,
 10246,
 10247,
 10248,
 10249,
 10250,
 10252,
 10253,
 10254,
 10255,
 10256,
 10257,
 10258,
 10259,
 10260,
 10261,
 10262,
 10263,
 10264,
 10265,
 10266,
 10267,
 10268,
 10269,
 10270,
 10271,
 10272,
 10273,
 10274,
 10275,
 10276,
 10277,
 10278,
 10279,
 10280,
 10281,
 10282,
 10283,
 10284,
 10285,
 10286,
 10287,
 10288,
 10289,
 10290,
 10292,
 10293,
 10294,
 10295,
 10296,
 10297,
 10298,
 10299,
 10300,
 10301,
 10302,
 10303,
 10304,
 10305,
 10306,
 10307,
 10308,
 10309,
 10312,
 10313,
 10314,
 10315,
 10316,
 10317,
 10318,
 10319,
 10320,
 10321,
 10322,
 10323,
 10324,
 10325,
 10326,
 10327,
 10328,
 10329,
 10330,
 10331,
 10332,
 10333,
 10334,
 10335,
 10336,
 10338,
 10339,
 10340,
 10341,
 10342,
 10343,
 10344,
 10345,
 10346,
 10347,
 10348,
 10350,
 10351,
 10352,
 10354,
 10355,
 10356,
 10357,
 10358,
 10359,
 10360,
 10361,
 10362,
 10363,
 10364,
 10365,
 10366,
 10367,
 10369,
 10370,
 10371,
 10372,
 10373,
 10374,
 10376,
 10377,
 10378,
 10379,
 10380,
 10381,
 10382,
 10383,
 10384,
 10385,
 10386,
 10387,
 10388,
 10389,
 10390,
 10391,
 10392,
 10393,
 10394,
 10395,
 10396,
 10397,
 10398,
 10399,
 10400,
 10401,
 10402,
 10403,
 10404,
 10405,
 10406,
 10407,
 10408,
 10409,
 10410,
 10411,
 10412,
 10413,
 10414,
 10415,
 10418,
 10421,
 10423,
 10424,
 10425,
 10426,
 10427,
 10428,
 10429,
 10430,
 10431,
 10432,
 10433,
 10434,
 10435,
 10436,
 10437,
 10438,
 10439,
 10440,
 10441,
 10442,
 10443,
 10444,
 10445,
 10446,
 10447,
 10448,
 10449,
 10450,
 10451,
 10452,
 10453,
 10454,
 10455,
 10456,
 10457,
 10458,
 10459,
 10460,
 10461,
 10462,
 10463,
 10464,
 10465,
 10466,
 10467,
 10468,
 10469,
 10470,
 10471,
 10472,
 10473,
 10474,
 10475,
 10476,
 10477,
 10478,
 10479,
 10480,
 10481,
 10482,
 10483,
 10484,
 10485,
 10486,
 10487,
 10488,
 10489,
 10490,
 10491,
 10492,
 10493,
 10494,
 10495,
 10496,
 10497,
 10498,
 10499,
 10500,
 10501,
 10502,
 10503,
 10504,
 10505,
 10506,
 10507,
 10508,
 10509,
 10510,
 10511,
 10512,
 10513,
 10514,
 10517,
 10533,
 10563,
 10564,
 10565,
 10566,
 10567,
 10568,
 10569,
 10570,
 10571,
 10572,
 10573,
 10574,
 10575,
 10576,
 10577,
 10578,
 10579,
 10580,
 10581,
 10582,
 10583,
 10584,
 10585,
 10587,
 10588,
 10593,
 10594,
 10595,
 10596,
 10597,
 10598,
 10599,
 10601,
 10602,
 10603,
 10604,
 10605,
 10606,
 10607,
 10608,
 10609,
 10610,
 10611,
 10612,
 10613,
 10615,
 10616,
 10618,
 10619,
 10620,
 10621,
 10622,
 10623,
 10624,
 10626,
 10627,
 10628,
 10629,
 10630,
 10631,
 10632,
 10633,
 10634,
 10635,
 10636,
 10637,
 10638,
 10639,
 10640,
 10641,
 10642,
 10643,
 10644,
 10645,
 10646,
 10647,
 10649,
 10650,
 10652,
 10654,
 10655,
 10656,
 10658,
 10660,
 10661,
 10662,
 10664,
 10665,
 10669,
 10670,
 10671,
 10672,
 10673,
 10674,
 10675,
 10676,
 10677,
 10678,
 10680,
 10681,
 10682,
 10683,
 10684,
 10685,
 10689,
 10690,
 10691,
 10692,
 10693,
 10694,
 10698,
 10699,
 10700,
 10701,
 10702,
 10704,
 10705,
 10706,
 10707,
 10708,
 10709,
 10710,
 10711,
 10712,
 10713,
 10714,
 10715,
 10716,
 10717,
 10718,
 10719,
 10720,
 10721,
 10722,
 10723,
 10724,
 10725,
 10726,
 10727,
 10728,
 10729,
 10730,
 10731,
 10732,
 10733,
 10734,
 10735,
 10736,
 10737,
 10738,
 10739,
 10740,
 10741,
 10742,
 10743,
 10744,
 10746,
 10747,
 10748,
 10749,
 10750,
 10751,
 10752,
 10753,
 10754,
 10755,
 10756,
 10757,
 10758,
 10759,
 10760,
 10761,
 10762,
 10763,
 10764,
 10765,
 10766,
 10767,
 10768,
 10769,
 10770,
 10771,
 10772,
 10773,
 10774,
 10775,
 10776,
 10777,
 10778,
 10783,
 10784,
 10785,
 10786,
 10787,
 10788,
 10789,
 10790,
 10791,
 10792,
 10793,
 10794,
 10795,
 10796,
 10797,
 10799,
 10800,
 10801,
 10802,
 10803,
 10804,
 10805,
 10806,
 10807,
 10809,
 10810,
 10811,
 10812,
 10813,
 10814,
 10815,
 10816,
 10817,
 10818,
 10819,
 10820,
 10821,
 10822,
 10823,
 10824,
 10825,
 10826,
 10827,
 10828,
 10829,
 10830,
 10831,
 10832,
 10833,
 10834,
 10835,
 10836,
 10837,
 10839,
 10840,
 10842,
 10843,
 10844,
 10845,
 10846,
 10848,
 10849,
 10850,
 10851,
 10852,
 10853,
 10854,
 10855,
 10856,
 10857,
 10858,
 10859,
 10861,
 10862,
 10863,
 10864,
 10865,
 10866,
 10867,
 10869,
 10870,
 10871,
 10872,
 10873,
 10874,
 10875,
 10876,
 10877,
 10878,
 10879,
 10880,
 10882,
 10883,
 10884,
 10885,
 10886,
 10987,
 10988,
 10989,
 10990,
 10991,
 10992,
 10993,
 10994,
 10995,
 10996,
 10997,
 10998,
 10999,
 11000,
 11001,
 11002,
 11003,
 11004,
 11005,
 11006,
 11007,
 11008,
 11009,
 11010,
 11011,
 11012,
 11013,
 11014,
 11015,
 11016,
 11017,
 11018,
 11019,
 11020,
 11021,
 11022,
 11023,
 11024,
 11025,
 11026,
 11027,
 11028,
 11029,
 11030,
 11031,
 11032,
 11033,
 11034,
 11035,
 11036,
 11037,
 11038,
 11039,
 11040,
 11041,
 11042,
 11043,
 11044,
 11045,
 11046,
 11047,
 11048,
 11049,
 11050,
 11051,
 11052,
 11053,
 11054,
 11055,
 11056,
 11057,
 11058,
 11059,
 11062,
 11063,
 11064,
 11067,
 11069,
 11070,
 11071,
 11072,
 11073,
 11074,
 11075,
 11076,
 11077,
 11078,
 11079,
 11080,
 11081,
 11082,
 11083,
 11084,
 11085,
 11086,
 11087,
 11088,
 11089,
 11090,
 11091,
 11092,
 11093,
 11094,
 11095,
 11096,
 11097,
 11098,
 11099,
 11100,
 11101,
 11102,
 11103,
 11104,
 11105,
 11106,
 11107,
 11108,
 11109,
 11110,
 11111,
 11112,
 11113,
 11114,
 11115,
 11116,
 11117,
 11118,
 11119,
 11121,
 11123,
 11124,
 11125,
 11126,
 11128,
 11129,
 11130,
 11131,
 11132,
 11133,
 11134,
 11135,
 11136,
 11138,
 11139,
 11140,
 11141,
 11142,
 11143,
 11144,
 11145,
 11146,
 11147,
 11148,
 11150,
 11151,
 11152,
 11153,
 11154,
 11155,
 11156,
 11157,
 11158,
 11159,
 11160,
 11161,
 11162,
 11163,
 11164,
 11165,
 11166,
 11167,
 11168,
 11169,
 11170,
 11171,
 11172,
 11173,
 11174,
 11175,
 11176,
 11178,
 11179,
 11180,
 11188,
 11191,
 11192,
 11193,
 11196,
 11198,
 11199,
 11200,
 11202,
 11203,
 11204,
 11205,
 11207,
 11208,
 11209,
 11210,
 11211,
 11212,
 11213,
 11214,
 11215,
 11216,
 11217,
 11218,
 11220,
 11221,
 11222,
 11223,
 11225,
 11226,
 11228,
 11229,
 11230,
 11231,
 11233,
 11234,
 11235,
 11236,
 11237,
 11239,
 11240,
 11241,
 11242,
 11243,
 11244,
 11245,
 11246,
 11247,
 11248,
 11250,
 11253,
 11254,
 11255,
 11256,
 11257,
 11258,
 11259,
 11260,
 11261,
 11262,
 ...]

In [79]:
ratings_list=[]
for i in range(100000):
    ratings_list.append(random.randint(0,5))
ratings_list

[3,
 2,
 0,
 5,
 3,
 1,
 0,
 0,
 2,
 1,
 5,
 3,
 1,
 4,
 0,
 4,
 3,
 0,
 3,
 5,
 2,
 3,
 4,
 0,
 5,
 3,
 5,
 4,
 1,
 2,
 0,
 2,
 1,
 1,
 1,
 2,
 4,
 3,
 5,
 4,
 2,
 4,
 3,
 4,
 1,
 4,
 4,
 5,
 1,
 5,
 1,
 0,
 5,
 2,
 4,
 4,
 0,
 4,
 4,
 3,
 4,
 0,
 2,
 5,
 2,
 5,
 5,
 5,
 5,
 0,
 2,
 1,
 3,
 3,
 3,
 1,
 1,
 0,
 1,
 1,
 3,
 1,
 0,
 5,
 3,
 0,
 4,
 4,
 2,
 5,
 1,
 3,
 5,
 3,
 5,
 2,
 0,
 4,
 1,
 2,
 4,
 1,
 1,
 2,
 1,
 0,
 3,
 1,
 4,
 4,
 3,
 0,
 4,
 5,
 3,
 5,
 4,
 3,
 4,
 5,
 2,
 2,
 4,
 4,
 0,
 0,
 3,
 1,
 2,
 0,
 1,
 5,
 3,
 3,
 0,
 3,
 4,
 0,
 4,
 4,
 2,
 4,
 4,
 3,
 1,
 2,
 3,
 5,
 5,
 2,
 4,
 5,
 2,
 3,
 1,
 5,
 5,
 2,
 3,
 1,
 2,
 4,
 5,
 5,
 2,
 5,
 0,
 1,
 0,
 1,
 4,
 4,
 1,
 4,
 0,
 3,
 0,
 1,
 1,
 2,
 0,
 4,
 5,
 5,
 3,
 0,
 3,
 5,
 0,
 3,
 5,
 0,
 4,
 1,
 0,
 1,
 5,
 2,
 3,
 2,
 1,
 4,
 5,
 4,
 2,
 1,
 4,
 4,
 4,
 0,
 4,
 0,
 2,
 0,
 1,
 0,
 4,
 2,
 0,
 0,
 4,
 1,
 1,
 4,
 4,
 5,
 5,
 5,
 0,
 2,
 4,
 0,
 0,
 0,
 3,
 1,
 3,
 0,
 1,
 4,
 4,
 0,
 5,
 3,
 2,
 5,
 2,
 1,
 2,
 4,
 5,
 3,
 2,
 3,
 0,
 4,
 1,
 3,
 2,
 1,
 0,
 5,
 2,
 4,
 4,
 3,
 1,
 1,
 0,
 5,
 0,
 4,
 0,
 0,
 2,
 3,
 3,
 4,
 2,
 2,
 1,
 1,
 1,
 3,
 5,
 2,
 5,
 3,
 0,
 5,
 0,
 1,
 5,
 3,
 5,
 0,
 1,
 1,
 3,
 1,
 5,
 4,
 5,
 3,
 0,
 0,
 1,
 0,
 4,
 0,
 0,
 1,
 2,
 0,
 0,
 2,
 0,
 3,
 0,
 5,
 4,
 5,
 0,
 1,
 4,
 3,
 2,
 4,
 2,
 2,
 3,
 1,
 0,
 4,
 2,
 1,
 1,
 1,
 2,
 0,
 3,
 5,
 0,
 0,
 1,
 1,
 1,
 4,
 4,
 3,
 4,
 4,
 1,
 3,
 3,
 0,
 5,
 5,
 5,
 5,
 3,
 1,
 1,
 1,
 4,
 0,
 2,
 0,
 1,
 1,
 0,
 1,
 0,
 5,
 5,
 5,
 2,
 0,
 1,
 4,
 0,
 4,
 5,
 1,
 1,
 3,
 0,
 2,
 4,
 0,
 2,
 2,
 5,
 2,
 2,
 2,
 1,
 4,
 1,
 4,
 5,
 1,
 0,
 1,
 2,
 5,
 4,
 4,
 3,
 5,
 3,
 0,
 2,
 0,
 2,
 4,
 5,
 2,
 3,
 4,
 0,
 1,
 0,
 4,
 4,
 5,
 5,
 0,
 0,
 3,
 3,
 5,
 3,
 0,
 5,
 4,
 2,
 3,
 0,
 1,
 4,
 0,
 3,
 5,
 3,
 1,
 2,
 0,
 3,
 0,
 4,
 1,
 5,
 2,
 0,
 1,
 2,
 0,
 2,
 3,
 2,
 4,
 3,
 0,
 2,
 5,
 1,
 2,
 3,
 1,
 4,
 4,
 5,
 3,
 1,
 2,
 1,
 5,
 0,
 4,
 2,
 0,
 4,
 5,
 0,
 0,
 5,
 2,
 0,
 2,
 2,
 2,
 1,
 3,
 5,
 4,
 4,
 1,
 4,
 3,
 1,
 2,
 4,
 5,
 5,
 5,
 3,
 1,
 1,
 4,
 1,
 4,
 2,
 0,
 5,
 5,
 4,
 4,
 0,
 2,
 3,
 3,
 1,
 1,
 4,
 4,
 0,
 4,
 5,
 4,
 3,
 5,
 4,
 2,
 2,
 5,
 0,
 3,
 0,
 2,
 0,
 4,
 0,
 5,
 3,
 0,
 3,
 1,
 5,
 0,
 2,
 2,
 1,
 0,
 4,
 2,
 1,
 3,
 1,
 5,
 0,
 5,
 3,
 0,
 0,
 3,
 0,
 1,
 2,
 4,
 3,
 1,
 0,
 3,
 0,
 1,
 2,
 4,
 1,
 1,
 5,
 2,
 4,
 0,
 0,
 3,
 1,
 5,
 2,
 5,
 1,
 3,
 3,
 5,
 3,
 1,
 3,
 3,
 0,
 0,
 1,
 1,
 3,
 1,
 4,
 4,
 4,
 4,
 3,
 1,
 3,
 5,
 5,
 1,
 4,
 0,
 3,
 3,
 1,
 1,
 4,
 5,
 4,
 0,
 0,
 3,
 2,
 2,
 1,
 0,
 2,
 3,
 4,
 3,
 5,
 5,
 0,
 4,
 4,
 2,
 1,
 3,
 4,
 3,
 5,
 5,
 1,
 0,
 3,
 0,
 1,
 4,
 5,
 4,
 3,
 0,
 2,
 1,
 2,
 0,
 4,
 3,
 2,
 1,
 5,
 1,
 1,
 2,
 2,
 5,
 0,
 2,
 5,
 3,
 1,
 3,
 1,
 3,
 0,
 2,
 4,
 5,
 0,
 3,
 2,
 4,
 0,
 5,
 2,
 1,
 1,
 4,
 5,
 2,
 4,
 3,
 2,
 0,
 5,
 2,
 5,
 5,
 0,
 0,
 0,
 3,
 0,
 1,
 3,
 1,
 4,
 0,
 1,
 3,
 2,
 1,
 4,
 0,
 5,
 1,
 1,
 3,
 3,
 2,
 1,
 2,
 2,
 5,
 1,
 0,
 5,
 5,
 0,
 0,
 2,
 3,
 0,
 0,
 4,
 5,
 0,
 4,
 1,
 3,
 0,
 2,
 3,
 5,
 4,
 3,
 1,
 2,
 3,
 2,
 2,
 3,
 1,
 2,
 3,
 4,
 4,
 4,
 2,
 2,
 4,
 5,
 2,
 5,
 5,
 4,
 1,
 0,
 1,
 0,
 2,
 5,
 1,
 4,
 2,
 4,
 2,
 2,
 3,
 4,
 0,
 2,
 0,
 5,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 4,
 1,
 3,
 3,
 0,
 3,
 4,
 1,
 3,
 2,
 1,
 5,
 5,
 3,
 0,
 1,
 5,
 5,
 3,
 3,
 5,
 0,
 3,
 4,
 3,
 0,
 3,
 4,
 0,
 1,
 2,
 3,
 3,
 4,
 2,
 1,
 3,
 4,
 1,
 5,
 4,
 0,
 1,
 1,
 1,
 1,
 3,
 5,
 2,
 4,
 0,
 0,
 2,
 4,
 0,
 3,
 4,
 0,
 4,
 0,
 0,
 5,
 5,
 0,
 3,
 1,
 5,
 2,
 0,
 1,
 3,
 1,
 3,
 2,
 2,
 1,
 1,
 1,
 2,
 5,
 4,
 5,
 2,
 5,
 3,
 2,
 0,
 5,
 2,
 0,
 0,
 0,
 1,
 2,
 1,
 3,
 4,
 5,
 2,
 2,
 2,
 3,
 4,
 1,
 0,
 0,
 3,
 5,
 3,
 0,
 2,
 1,
 2,
 2,
 5,
 5,
 5,
 5,
 2,
 0,
 5,
 5,
 3,
 3,
 0,
 3,
 3,
 0,
 0,
 4,
 1,
 5,
 4,
 1,
 4,
 5,
 0,
 2,
 2,
 5,
 0,
 0,
 1,
 5,
 2,
 1,
 4,
 3,
 2,
 3,
 5,
 4,
 1,
 5,
 1,
 1,
 1,
 0,
 3,
 1,
 5,
 5,
 3,
 4,
 0,
 2,
 0,
 3,
 1,
 4,
 0,
 2,
 2,
 4,
 0,
 0,
 2,
 1,
 3,
 5,
 5,
 0,
 2,
 5,
 2,
 0,
 5,
 2,
 5,
 1,
 4,
 4,
 5,
 1,
 1,
 2,
 4,
 2,
 1,
 4,
 2,
 1,
 3,
 1,
 ...]

In [80]:
products_list=[]
for i in range(100000):
    products_list.append(random.choice(product_id))
products_list

[6327,
 22043,
 55071,
 32236,
 24053,
 46677,
 42110,
 31995,
 10145,
 2274,
 49138,
 47642,
 44004,
 43710,
 13779,
 30850,
 28732,
 18471,
 4237,
 19148,
 27719,
 48891,
 56942,
 12865,
 23650,
 17580,
 8289,
 34985,
 53360,
 3227,
 6704,
 10224,
 33611,
 55148,
 14605,
 30575,
 44622,
 37457,
 5189,
 18357,
 2272,
 46738,
 58445,
 36068,
 45835,
 24671,
 10288,
 12581,
 53067,
 9950,
 55361,
 11853,
 22913,
 14359,
 41427,
 49475,
 11146,
 26616,
 43323,
 32949,
 51461,
 56107,
 31601,
 44695,
 3909,
 54403,
 33366,
 15092,
 4376,
 47270,
 38418,
 30799,
 43106,
 59049,
 34923,
 13778,
 25707,
 18538,
 17239,
 59980,
 47068,
 20938,
 10030,
 14116,
 33701,
 42331,
 15985,
 20432,
 28755,
 4636,
 2542,
 58298,
 50554,
 27912,
 42045,
 50305,
 42097,
 24589,
 20374,
 43000,
 49023,
 50281,
 32841,
 42924,
 32039,
 40498,
 29247,
 55093,
 36354,
 57303,
 50164,
 58611,
 42908,
 50473,
 51582,
 39176,
 19639,
 34918,
 53666,
 11454,
 16865,
 50016,
 3680,
 8574,
 44192,
 34199,
 14565,
 45968,
 4449,
 41665,
 44961,
 36482,
 18613,
 27893,
 8885,
 39315,
 26433,
 35802,
 14833,
 4605,
 7561,
 12865,
 17806,
 36796,
 59896,
 24409,
 38242,
 47332,
 36272,
 24975,
 4002,
 32427,
 56147,
 30776,
 14652,
 44997,
 33519,
 25226,
 46894,
 5142,
 19348,
 39997,
 14623,
 59575,
 13215,
 15172,
 59928,
 50149,
 4009,
 3275,
 56996,
 51940,
 5895,
 9819,
 49940,
 34985,
 56269,
 38126,
 29747,
 15687,
 42062,
 6561,
 38830,
 18526,
 41696,
 18859,
 37248,
 52876,
 22110,
 17979,
 22276,
 56904,
 12717,
 37285,
 25835,
 27900,
 55320,
 15022,
 17246,
 28885,
 40455,
 14976,
 6108,
 18408,
 13689,
 28236,
 33986,
 38900,
 17189,
 35231,
 8476,
 6055,
 34451,
 24229,
 2885,
 59286,
 1542,
 12896,
 16761,
 54529,
 40307,
 30066,
 31115,
 42144,
 55836,
 23812,
 7909,
 31938,
 13907,
 18673,
 13000,
 6997,
 52222,
 48700,
 6147,
 49772,
 12849,
 39017,
 24188,
 4747,
 55155,
 46159,
 20176,
 40599,
 13418,
 45441,
 49713,
 44214,
 14872,
 52220,
 45659,
 7144,
 20966,
 15269,
 52910,
 56928,
 23276,
 49868,
 3553,
 59115,
 34297,
 18779,
 54842,
 3323,
 52150,
 22677,
 1888,
 22310,
 8936,
 34995,
 40009,
 53867,
 33101,
 15567,
 14497,
 20205,
 35242,
 47548,
 16101,
 13389,
 53591,
 53556,
 48489,
 59748,
 21340,
 39503,
 40325,
 49144,
 10059,
 51499,
 38333,
 50201,
 7476,
 13640,
 7115,
 12052,
 14494,
 56365,
 38443,
 37686,
 27717,
 33645,
 50435,
 21588,
 7066,
 12947,
 54907,
 17042,
 13346,
 51694,
 2587,
 37244,
 12427,
 56665,
 38440,
 48346,
 52998,
 58958,
 17712,
 12148,
 19800,
 13539,
 4186,
 39270,
 36230,
 49480,
 19222,
 58292,
 14837,
 4673,
 44731,
 19619,
 12003,
 48897,
 23543,
 24964,
 6220,
 17321,
 32008,
 17207,
 17116,
 8361,
 40758,
 6167,
 12827,
 34205,
 13416,
 51661,
 47434,
 15162,
 45925,
 45217,
 25102,
 39490,
 44038,
 40436,
 36064,
 47565,
 33543,
 7870,
 50203,
 2342,
 11976,
 25004,
 52897,
 23819,
 19262,
 44068,
 19974,
 49857,
 17984,
 24357,
 14843,
 56361,
 58475,
 3213,
 46588,
 8847,
 59273,
 26491,
 39821,
 35464,
 16341,
 55423,
 40482,
 31142,
 41387,
 48217,
 56530,
 57973,
 37857,
 26049,
 55057,
 34116,
 17786,
 28937,
 10111,
 29036,
 39040,
 18694,
 9367,
 34060,
 18276,
 34328,
 55250,
 33838,
 18993,
 4044,
 48116,
 2686,
 46632,
 9672,
 17303,
 25712,
 24928,
 23550,
 44421,
 11375,
 7751,
 34921,
 43083,
 41988,
 47350,
 15223,
 48866,
 14122,
 48469,
 21572,
 52090,
 15467,
 25961,
 59528,
 28554,
 49270,
 38295,
 53454,
 42331,
 16059,
 18393,
 53624,
 5272,
 30636,
 41212,
 58208,
 24606,
 30466,
 28973,
 48573,
 11548,
 2217,
 30839,
 4034,
 48946,
 31782,
 55650,
 9583,
 4808,
 32433,
 16519,
 27590,
 37871,
 47323,
 30848,
 54020,
 59579,
 41760,
 42914,
 37870,
 7862,
 11530,
 57127,
 23316,
 3898,
 2922,
 11090,
 12540,
 36710,
 38121,
 48604,
 11415,
 35697,
 33922,
 15637,
 37172,
 6447,
 12118,
 56488,
 28266,
 42818,
 56267,
 39553,
 7853,
 56177,
 52801,
 58191,
 21782,
 59635,
 33700,
 52147,
 16804,
 15041,
 20104,
 51334,
 24500,
 34219,
 32431,
 52345,
 14097,
 2481,
 13838,
 51765,
 49521,
 56817,
 36757,
 2211,
 47162,
 23468,
 43703,
 4053,
 28775,
 49736,
 50323,
 38993,
 32534,
 12092,
 23529,
 29926,
 44741,
 15971,
 46444,
 31213,
 32830,
 30752,
 25782,
 50664,
 55155,
 19386,
 27839,
 8879,
 34103,
 14071,
 31340,
 33377,
 15462,
 52791,
 10256,
 13630,
 48242,
 4517,
 7309,
 10355,
 15514,
 19688,
 11059,
 48787,
 13290,
 10193,
 54058,
 29511,
 36416,
 6789,
 35143,
 11515,
 39640,
 52834,
 7066,
 34632,
 28957,
 13302,
 48196,
 28609,
 16739,
 6043,
 50193,
 10168,
 9537,
 28757,
 22711,
 26474,
 15840,
 51352,
 27021,
 47032,
 39620,
 33533,
 9955,
 25945,
 24701,
 29821,
 52477,
 45633,
 28739,
 38624,
 30837,
 6498,
 18945,
 46651,
 33383,
 42237,
 30255,
 29734,
 24426,
 36034,
 19319,
 8956,
 11381,
 23163,
 36818,
 31895,
 55259,
 46462,
 10762,
 19087,
 9918,
 8477,
 57664,
 15303,
 17731,
 49938,
 22600,
 52355,
 16323,
 14168,
 56329,
 40644,
 26855,
 43620,
 59094,
 18689,
 54050,
 39758,
 19037,
 28272,
 2365,
 24111,
 26447,
 32043,
 21574,
 50606,
 22248,
 33753,
 30888,
 56531,
 26203,
 41944,
 43327,
 11736,
 25218,
 31634,
 19508,
 50944,
 29946,
 33300,
 43366,
 46455,
 36409,
 58680,
 3187,
 26948,
 14897,
 54695,
 27786,
 54904,
 15349,
 18273,
 17289,
 17712,
 42960,
 30891,
 32485,
 57319,
 20735,
 31942,
 15687,
 59544,
 17541,
 43492,
 49546,
 7504,
 46537,
 56539,
 19683,
 45193,
 5280,
 10655,
 2257,
 43260,
 37474,
 20223,
 28617,
 56906,
 55976,
 15235,
 5622,
 50515,
 39311,
 7790,
 26988,
 13372,
 42538,
 37754,
 44765,
 46425,
 31934,
 24633,
 47365,
 50621,
 5442,
 37298,
 56951,
 17576,
 43851,
 12372,
 45723,
 6626,
 2093,
 31564,
 44441,
 40289,
 6188,
 37633,
 39981,
 27994,
 42899,
 4312,
 25762,
 21274,
 18996,
 29100,
 47223,
 7096,
 31800,
 3390,
 29246,
 58306,
 11829,
 37608,
 16514,
 28854,
 11773,
 56119,
 37723,
 12544,
 4407,
 14902,
 35025,
 52802,
 3104,
 57163,
 46553,
 5808,
 44898,
 48258,
 10475,
 3715,
 42850,
 18817,
 37594,
 54641,
 14940,
 16755,
 4751,
 34023,
 15255,
 26969,
 38328,
 13065,
 56392,
 10229,
 51602,
 25187,
 19142,
 13928,
 34089,
 23113,
 48755,
 52799,
 19303,
 45736,
 1617,
 58177,
 38489,
 52481,
 28769,
 15285,
 52493,
 25960,
 54194,
 49587,
 52088,
 1728,
 38414,
 53040,
 45838,
 47294,
 35182,
 16624,
 56363,
 43679,
 8664,
 51524,
 27478,
 23693,
 54863,
 48618,
 7486,
 29024,
 59711,
 37732,
 46609,
 8235,
 52084,
 6088,
 45265,
 34340,
 43132,
 20482,
 36540,
 59257,
 44573,
 57716,
 33827,
 20957,
 4100,
 25669,
 56698,
 56914,
 20051,
 29006,
 34177,
 50884,
 12163,
 19380,
 21016,
 19180,
 58027,
 36498,
 11256,
 30852,
 36804,
 16959,
 52355,
 7391,
 30029,
 33692,
 7859,
 3044,
 10747,
 53374,
 5575,
 33900,
 17305,
 3898,
 43937,
 46162,
 51767,
 18843,
 1932,
 28898,
 24648,
 4142,
 9503,
 17774,
 27148,
 20454,
 51612,
 38787,
 2003,
 15625,
 37249,
 10288,
 53652,
 4508,
 55628,
 49113,
 50181,
 42077,
 36506,
 39292,
 3623,
 54951,
 52987,
 21886,
 54665,
 12529,
 1644,
 46935,
 10858,
 9986,
 21021,
 26225,
 34439,
 8754,
 5934,
 48075,
 37278,
 43588,
 22573,
 31942,
 50991,
 40689,
 58411,
 36933,
 28889,
 5761,
 47045,
 44197,
 9615,
 8843,
 46484,
 47047,
 26336,
 15073,
 40433,
 43311,
 27699,
 13315,
 44465,
 40467,
 44056,
 39508,
 5599,
 5722,
 28472,
 20685,
 13406,
 44751,
 7794,
 19291,
 43362,
 29498,
 2187,
 16748,
 37728,
 24334,
 8262,
 33137,
 53632,
 9170,
 38466,
 47581,
 25617,
 31186,
 27021,
 13475,
 16318,
 17236,
 3648,
 23542,
 55463,
 49741,
 16129,
 11358,
 42308,
 47196,
 18739,
 49589,
 3127,
 5803,
 23336,
 10306,
 30640,
 10383,
 48206,
 21450,
 4396,
 20364,
 34889,
 46273,
 9383,
 25834,
 58301,
 38488,
 11643,
 4512,
 13763,
 16096,
 57920,
 50404,
 18278,
 41404,
 20578,
 4845,
 43751,
 6882,
 49373,
 57343,
 37229,
 17104,
 14478,
 34410,
 19536,
 8845,
 44118,
 45121,
 55994,
 12587,
 43523,
 41406,
 32462,
 ...]

In [81]:
users=[]
for i in range(1000):
    users.append(i+1000)
users

[1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1037,
 1038,
 1039,
 1040,
 1041,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1048,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1058,
 1059,
 1060,
 1061,
 1062,
 1063,
 1064,
 1065,
 1066,
 1067,
 1068,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1080,
 1081,
 1082,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1095,
 1096,
 1097,
 1098,
 1099,
 1100,
 1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1215,
 1216,
 1217,
 1218,
 1219,
 1220,
 1221,
 1222,
 1223,
 1224,
 1225,
 1226,
 1227,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1239,
 1240,
 1241,
 1242,
 1243,
 1244,
 1245,
 1246,
 1247,
 1248,
 1249,
 1250,
 1251,
 1252,
 1253,
 1254,
 1255,
 1256,
 1257,
 1258,
 1259,
 1260,
 1261,
 1262,
 1263,
 1264,
 1265,
 1266,
 1267,
 1268,
 1269,
 1270,
 1271,
 1272,
 1273,
 1274,
 1275,
 1276,
 1277,
 1278,
 1279,
 1280,
 1281,
 1282,
 1283,
 1284,
 1285,
 1286,
 1287,
 1288,
 1289,
 1290,
 1291,
 1292,
 1293,
 1294,
 1295,
 1296,
 1297,
 1298,
 1299,
 1300,
 1301,
 1302,
 1303,
 1304,
 1305,
 1306,
 1307,
 1308,
 1309,
 1310,
 1311,
 1312,
 1313,
 1314,
 1315,
 1316,
 1317,
 1318,
 1319,
 1320,
 1321,
 1322,
 1323,
 1324,
 1325,
 1326,
 1327,
 1328,
 1329,
 1330,
 1331,
 1332,
 1333,
 1334,
 1335,
 1336,
 1337,
 1338,
 1339,
 1340,
 1341,
 1342,
 1343,
 1344,
 1345,
 1346,
 1347,
 1348,
 1349,
 1350,
 1351,
 1352,
 1353,
 1354,
 1355,
 1356,
 1357,
 1358,
 1359,
 1360,
 1361,
 1362,
 1363,
 1364,
 1365,
 1366,
 1367,
 1368,
 1369,
 1370,
 1371,
 1372,
 1373,
 1374,
 1375,
 1376,
 1377,
 1378,
 1379,
 1380,
 1381,
 1382,
 1383,
 1384,
 1385,
 1386,
 1387,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1399,
 1400,
 1401,
 1402,
 1403,
 1404,
 1405,
 1406,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1418,
 1419,
 1420,
 1421,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1435,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1449,
 1450,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1462,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1469,
 1470,
 1471,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1479,
 1480,
 1481,
 1482,
 1483,
 1484,
 1485,
 1486,
 1487,
 1488,
 1489,
 1490,
 1491,
 1492,
 1493,
 1494,
 1495,
 1496,
 1497,
 1498,
 1499,
 1500,
 1501,
 1502,
 1503,
 1504,
 1505,
 1506,
 1507,
 1508,
 1509,
 1510,
 1511,
 1512,
 1513,
 1514,
 1515,
 1516,
 1517,
 1518,
 1519,
 1520,
 1521,
 1522,
 1523,
 1524,
 1525,
 1526,
 1527,
 1528,
 1529,
 1530,
 1531,
 1532,
 1533,
 1534,
 1535,
 1536,
 1537,
 1538,
 1539,
 1540,
 1541,
 1542,
 1543,
 1544,
 1545,
 1546,
 1547,
 1548,
 1549,
 1550,
 1551,
 1552,
 1553,
 1554,
 1555,
 1556,
 1557,
 1558,
 1559,
 1560,
 1561,
 1562,
 1563,
 1564,
 1565,
 1566,
 1567,
 1568,
 1569,
 1570,
 1571,
 1572,
 1573,
 1574,
 1575,
 1576,
 1577,
 1578,
 1579,
 1580,
 1581,
 1582,
 1583,
 1584,
 1585,
 1586,
 1587,
 1588,
 1589,
 1590,
 1591,
 1592,
 1593,
 1594,
 1595,
 1596,
 1597,
 1598,
 1599,
 1600,
 1601,
 1602,
 1603,
 1604,
 1605,
 1606,
 1607,
 1608,
 1609,
 1610,
 1611,
 1612,
 1613,
 1614,
 1615,
 1616,
 1617,
 1618,
 1619,
 1620,
 1621,
 1622,
 1623,
 1624,
 1625,
 1626,
 1627,
 1628,
 1629,
 1630,
 1631,
 1632,
 1633,
 1634,
 1635,
 1636,
 1637,
 1638,
 1639,
 1640,
 1641,
 1642,
 1643,
 1644,
 1645,
 1646,
 1647,
 1648,
 1649,
 1650,
 1651,
 1652,
 1653,
 1654,
 1655,
 1656,
 1657,
 1658,
 1659,
 1660,
 1661,
 1662,
 1663,
 1664,
 1665,
 1666,
 1667,
 1668,
 1669,
 1670,
 1671,
 1672,
 1673,
 1674,
 1675,
 1676,
 1677,
 1678,
 1679,
 1680,
 1681,
 1682,
 1683,
 1684,
 1685,
 1686,
 1687,
 1688,
 1689,
 1690,
 1691,
 1692,
 1693,
 1694,
 1695,
 1696,
 1697,
 1698,
 1699,
 1700,
 1701,
 1702,
 1703,
 1704,
 1705,
 1706,
 1707,
 1708,
 1709,
 1710,
 1711,
 1712,
 1713,
 1714,
 1715,
 1716,
 1717,
 1718,
 1719,
 1720,
 1721,
 1722,
 1723,
 1724,
 1725,
 1726,
 1727,
 1728,
 1729,
 1730,
 1731,
 1732,
 1733,
 1734,
 1735,
 1736,
 1737,
 1738,
 1739,
 1740,
 1741,
 1742,
 1743,
 1744,
 1745,
 1746,
 1747,
 1748,
 1749,
 1750,
 1751,
 1752,
 1753,
 1754,
 1755,
 1756,
 1757,
 1758,
 1759,
 1760,
 1761,
 1762,
 1763,
 1764,
 1765,
 1766,
 1767,
 1768,
 1769,
 1770,
 1771,
 1772,
 1773,
 1774,
 1775,
 1776,
 1777,
 1778,
 1779,
 1780,
 1781,
 1782,
 1783,
 1784,
 1785,
 1786,
 1787,
 1788,
 1789,
 1790,
 1791,
 1792,
 1793,
 1794,
 1795,
 1796,
 1797,
 1798,
 1799,
 1800,
 1801,
 1802,
 1803,
 1804,
 1805,
 1806,
 1807,
 1808,
 1809,
 1810,
 1811,
 1812,
 1813,
 1814,
 1815,
 1816,
 1817,
 1818,
 1819,
 1820,
 1821,
 1822,
 1823,
 1824,
 1825,
 1826,
 1827,
 1828,
 1829,
 1830,
 1831,
 1832,
 1833,
 1834,
 1835,
 1836,
 1837,
 1838,
 1839,
 1840,
 1841,
 1842,
 1843,
 1844,
 1845,
 1846,
 1847,
 1848,
 1849,
 1850,
 1851,
 1852,
 1853,
 1854,
 1855,
 1856,
 1857,
 1858,
 1859,
 1860,
 1861,
 1862,
 1863,
 1864,
 1865,
 1866,
 1867,
 1868,
 1869,
 1870,
 1871,
 1872,
 1873,
 1874,
 1875,
 1876,
 1877,
 1878,
 1879,
 1880,
 1881,
 1882,
 1883,
 1884,
 1885,
 1886,
 1887,
 1888,
 1889,
 1890,
 1891,
 1892,
 1893,
 1894,
 1895,
 1896,
 1897,
 1898,
 1899,
 1900,
 1901,
 1902,
 1903,
 1904,
 1905,
 1906,
 1907,
 1908,
 1909,
 1910,
 1911,
 1912,
 1913,
 1914,
 1915,
 1916,
 1917,
 1918,
 1919,
 1920,
 1921,
 1922,
 1923,
 1924,
 1925,
 1926,
 1927,
 1928,
 1929,
 1930,
 1931,
 1932,
 1933,
 1934,
 1935,
 1936,
 1937,
 1938,
 1939,
 1940,
 1941,
 1942,
 1943,
 1944,
 1945,
 1946,
 1947,
 1948,
 1949,
 1950,
 1951,
 1952,
 1953,
 1954,
 1955,
 1956,
 1957,
 1958,
 1959,
 1960,
 1961,
 1962,
 1963,
 1964,
 1965,
 1966,
 1967,
 1968,
 1969,
 1970,
 1971,
 1972,
 1973,
 1974,
 1975,
 1976,
 1977,
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999]

In [82]:
users_list=[]
for i in range(100000):
    users_list.append(random.choice(users))
users_list

[1711,
 1132,
 1900,
 1548,
 1273,
 1514,
 1302,
 1670,
 1629,
 1722,
 1470,
 1505,
 1541,
 1677,
 1321,
 1653,
 1372,
 1594,
 1743,
 1712,
 1892,
 1292,
 1878,
 1468,
 1983,
 1426,
 1228,
 1451,
 1389,
 1068,
 1641,
 1745,
 1608,
 1436,
 1044,
 1886,
 1228,
 1362,
 1712,
 1165,
 1267,
 1338,
 1259,
 1861,
 1324,
 1955,
 1627,
 1199,
 1200,
 1182,
 1896,
 1635,
 1319,
 1073,
 1099,
 1132,
 1883,
 1781,
 1596,
 1862,
 1788,
 1117,
 1115,
 1509,
 1904,
 1313,
 1357,
 1955,
 1220,
 1511,
 1471,
 1544,
 1485,
 1889,
 1143,
 1945,
 1293,
 1262,
 1754,
 1111,
 1279,
 1874,
 1801,
 1114,
 1259,
 1284,
 1063,
 1025,
 1965,
 1430,
 1445,
 1310,
 1890,
 1475,
 1764,
 1902,
 1355,
 1297,
 1597,
 1580,
 1356,
 1363,
 1667,
 1759,
 1449,
 1369,
 1611,
 1782,
 1687,
 1611,
 1535,
 1080,
 1739,
 1754,
 1730,
 1867,
 1649,
 1357,
 1346,
 1180,
 1733,
 1440,
 1264,
 1449,
 1954,
 1341,
 1701,
 1250,
 1958,
 1949,
 1540,
 1514,
 1873,
 1037,
 1039,
 1601,
 1884,
 1518,
 1499,
 1092,
 1778,
 1365,
 1945,
 1747,
 1547,
 1741,
 1199,
 1695,
 1155,
 1515,
 1724,
 1691,
 1337,
 1214,
 1962,
 1211,
 1877,
 1731,
 1523,
 1792,
 1940,
 1561,
 1134,
 1741,
 1363,
 1789,
 1982,
 1295,
 1637,
 1052,
 1684,
 1420,
 1077,
 1462,
 1589,
 1565,
 1341,
 1890,
 1705,
 1864,
 1043,
 1205,
 1880,
 1623,
 1548,
 1970,
 1097,
 1249,
 1490,
 1345,
 1487,
 1426,
 1809,
 1988,
 1252,
 1826,
 1206,
 1067,
 1931,
 1921,
 1844,
 1569,
 1185,
 1510,
 1004,
 1916,
 1097,
 1119,
 1209,
 1503,
 1595,
 1595,
 1226,
 1280,
 1429,
 1564,
 1478,
 1218,
 1369,
 1869,
 1658,
 1830,
 1897,
 1881,
 1005,
 1989,
 1793,
 1253,
 1543,
 1490,
 1722,
 1310,
 1895,
 1297,
 1560,
 1857,
 1475,
 1039,
 1909,
 1223,
 1975,
 1431,
 1317,
 1658,
 1446,
 1600,
 1405,
 1597,
 1922,
 1122,
 1526,
 1680,
 1142,
 1046,
 1803,
 1459,
 1869,
 1742,
 1574,
 1565,
 1281,
 1956,
 1372,
 1475,
 1315,
 1223,
 1523,
 1212,
 1583,
 1303,
 1275,
 1301,
 1080,
 1256,
 1344,
 1294,
 1017,
 1292,
 1339,
 1047,
 1681,
 1469,
 1093,
 1637,
 1929,
 1771,
 1263,
 1319,
 1381,
 1712,
 1469,
 1384,
 1801,
 1588,
 1931,
 1517,
 1743,
 1896,
 1905,
 1702,
 1323,
 1997,
 1804,
 1628,
 1919,
 1113,
 1622,
 1353,
 1138,
 1392,
 1296,
 1882,
 1662,
 1055,
 1326,
 1817,
 1519,
 1836,
 1202,
 1510,
 1530,
 1772,
 1036,
 1046,
 1222,
 1604,
 1500,
 1428,
 1375,
 1205,
 1744,
 1923,
 1454,
 1539,
 1411,
 1289,
 1509,
 1137,
 1865,
 1362,
 1098,
 1777,
 1246,
 1461,
 1567,
 1491,
 1035,
 1784,
 1155,
 1596,
 1153,
 1952,
 1658,
 1869,
 1175,
 1250,
 1411,
 1660,
 1760,
 1912,
 1348,
 1465,
 1585,
 1058,
 1689,
 1900,
 1151,
 1684,
 1158,
 1834,
 1346,
 1488,
 1381,
 1413,
 1712,
 1681,
 1765,
 1618,
 1625,
 1887,
 1018,
 1812,
 1813,
 1006,
 1206,
 1419,
 1935,
 1470,
 1344,
 1619,
 1548,
 1553,
 1600,
 1055,
 1215,
 1944,
 1739,
 1768,
 1412,
 1890,
 1025,
 1799,
 1425,
 1886,
 1757,
 1836,
 1061,
 1850,
 1097,
 1240,
 1092,
 1712,
 1837,
 1073,
 1002,
 1252,
 1751,
 1227,
 1480,
 1406,
 1897,
 1898,
 1338,
 1771,
 1151,
 1847,
 1742,
 1303,
 1244,
 1668,
 1570,
 1332,
 1527,
 1787,
 1604,
 1055,
 1142,
 1066,
 1597,
 1952,
 1047,
 1512,
 1618,
 1059,
 1765,
 1260,
 1845,
 1678,
 1990,
 1785,
 1178,
 1606,
 1360,
 1442,
 1156,
 1995,
 1128,
 1741,
 1233,
 1436,
 1862,
 1315,
 1307,
 1886,
 1455,
 1433,
 1369,
 1044,
 1517,
 1971,
 1348,
 1791,
 1776,
 1484,
 1875,
 1814,
 1953,
 1667,
 1345,
 1072,
 1211,
 1854,
 1559,
 1078,
 1543,
 1466,
 1566,
 1884,
 1199,
 1079,
 1556,
 1822,
 1692,
 1910,
 1342,
 1628,
 1470,
 1961,
 1890,
 1993,
 1726,
 1493,
 1744,
 1039,
 1539,
 1383,
 1708,
 1817,
 1723,
 1424,
 1999,
 1755,
 1027,
 1763,
 1579,
 1200,
 1537,
 1501,
 1542,
 1761,
 1028,
 1000,
 1139,
 1889,
 1174,
 1060,
 1781,
 1078,
 1958,
 1663,
 1376,
 1966,
 1774,
 1561,
 1850,
 1585,
 1178,
 1407,
 1807,
 1748,
 1489,
 1056,
 1374,
 1938,
 1084,
 1675,
 1976,
 1936,
 1598,
 1297,
 1497,
 1078,
 1722,
 1550,
 1381,
 1247,
 1051,
 1664,
 1782,
 1995,
 1475,
 1159,
 1584,
 1336,
 1981,
 1022,
 1765,
 1723,
 1268,
 1330,
 1928,
 1990,
 1140,
 1860,
 1564,
 1034,
 1332,
 1121,
 1671,
 1767,
 1132,
 1541,
 1165,
 1117,
 1198,
 1353,
 1871,
 1345,
 1960,
 1258,
 1736,
 1967,
 1769,
 1057,
 1701,
 1864,
 1777,
 1123,
 1382,
 1588,
 1479,
 1333,
 1252,
 1474,
 1959,
 1368,
 1718,
 1893,
 1539,
 1655,
 1373,
 1352,
 1138,
 1429,
 1254,
 1527,
 1535,
 1476,
 1286,
 1519,
 1181,
 1448,
 1040,
 1223,
 1545,
 1144,
 1451,
 1129,
 1971,
 1267,
 1859,
 1002,
 1197,
 1290,
 1536,
 1766,
 1563,
 1320,
 1503,
 1325,
 1302,
 1362,
 1402,
 1361,
 1792,
 1204,
 1521,
 1395,
 1222,
 1394,
 1373,
 1593,
 1533,
 1958,
 1656,
 1840,
 1618,
 1591,
 1326,
 1717,
 1971,
 1865,
 1209,
 1397,
 1146,
 1509,
 1911,
 1250,
 1824,
 1028,
 1376,
 1167,
 1765,
 1539,
 1815,
 1387,
 1594,
 1586,
 1378,
 1377,
 1986,
 1473,
 1527,
 1546,
 1939,
 1217,
 1154,
 1661,
 1541,
 1324,
 1016,
 1833,
 1154,
 1121,
 1123,
 1390,
 1626,
 1921,
 1625,
 1297,
 1918,
 1781,
 1795,
 1565,
 1188,
 1043,
 1293,
 1823,
 1982,
 1900,
 1408,
 1636,
 1628,
 1432,
 1701,
 1332,
 1170,
 1709,
 1917,
 1101,
 1398,
 1266,
 1843,
 1632,
 1372,
 1275,
 1270,
 1475,
 1170,
 1535,
 1165,
 1221,
 1123,
 1992,
 1093,
 1943,
 1900,
 1609,
 1530,
 1087,
 1199,
 1264,
 1428,
 1377,
 1673,
 1393,
 1898,
 1440,
 1949,
 1191,
 1779,
 1361,
 1172,
 1494,
 1447,
 1283,
 1396,
 1708,
 1852,
 1038,
 1990,
 1570,
 1157,
 1407,
 1324,
 1619,
 1566,
 1764,
 1961,
 1890,
 1042,
 1533,
 1961,
 1661,
 1702,
 1276,
 1401,
 1086,
 1062,
 1782,
 1948,
 1821,
 1876,
 1189,
 1697,
 1203,
 1475,
 1844,
 1645,
 1099,
 1607,
 1427,
 1434,
 1487,
 1223,
 1145,
 1446,
 1259,
 1578,
 1388,
 1167,
 1409,
 1380,
 1434,
 1646,
 1544,
 1650,
 1491,
 1398,
 1091,
 1201,
 1944,
 1256,
 1648,
 1099,
 1562,
 1217,
 1485,
 1317,
 1321,
 1857,
 1641,
 1713,
 1468,
 1840,
 1616,
 1910,
 1005,
 1575,
 1995,
 1852,
 1016,
 1774,
 1067,
 1121,
 1194,
 1328,
 1405,
 1731,
 1750,
 1473,
 1577,
 1110,
 1167,
 1580,
 1030,
 1774,
 1399,
 1905,
 1966,
 1285,
 1622,
 1138,
 1836,
 1715,
 1223,
 1148,
 1777,
 1076,
 1895,
 1673,
 1642,
 1063,
 1624,
 1143,
 1116,
 1258,
 1222,
 1690,
 1826,
 1895,
 1277,
 1736,
 1989,
 1699,
 1144,
 1130,
 1796,
 1582,
 1534,
 1580,
 1901,
 1467,
 1537,
 1157,
 1607,
 1597,
 1151,
 1127,
 1317,
 1646,
 1017,
 1289,
 1237,
 1718,
 1103,
 1940,
 1315,
 1719,
 1562,
 1725,
 1205,
 1679,
 1311,
 1489,
 1894,
 1322,
 1715,
 1681,
 1111,
 1106,
 1716,
 1453,
 1647,
 1499,
 1428,
 1716,
 1392,
 1482,
 1035,
 1114,
 1922,
 1237,
 1228,
 1086,
 1275,
 1998,
 1914,
 1173,
 1876,
 1572,
 1385,
 1080,
 1609,
 1626,
 1405,
 1377,
 1845,
 1946,
 1764,
 1620,
 1509,
 1468,
 1956,
 1134,
 1153,
 1438,
 1576,
 1858,
 1501,
 1033,
 1399,
 1937,
 1059,
 1885,
 1430,
 1486,
 1696,
 1161,
 1303,
 1689,
 1223,
 1099,
 1755,
 1823,
 1591,
 1543,
 1739,
 1862,
 1776,
 1133,
 1953,
 1969,
 1488,
 1850,
 1945,
 1249,
 1938,
 1945,
 1600,
 1904,
 1998,
 1634,
 1789,
 1476,
 1505,
 1437,
 1703,
 1891,
 1933,
 1356,
 1514,
 1695,
 1004,
 1270,
 1416,
 1087,
 1269,
 1941,
 1534,
 ...]

In [83]:
transactions=pd.Series(transactions_list,name='Transactions_id')
users=pd.Series(users_list,name='User_id')
products=pd.Series(products_list,name='Products')
ratings=pd.Series(ratings_list,name='Ratings')

In [84]:
new_dff=pd.concat([transactions,users,products,ratings],axis=1)
new_dff

       Transactions_id  User_id  Products  Ratings
0               200000     1711      6327        3
1               200001     1132     22043        2
2               200002     1900     55071        0
3               200003     1548     32236        5
4               200004     1273     24053        3
...                ...      ...       ...      ...
99995           299995     1960     32614        4
99996           299996     1780     23875        5
99997           299997     1430     11986        2
99998           299998     1001     23214        2
99999           299999     1131     12568        4

[100000 rows x 4 columns]

In [85]:
new_dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Transactions_id  100000 non-null  int64
 1   User_id          100000 non-null  int64
 2   Products         100000 non-null  int64
 3   Ratings          100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

In [86]:
new_dff.to_csv('transactions.csv', header=True, index=False)
print('File Saved')

File Saved

In [87]:
df=pd.read_csv('transactions.csv')
df.head()

   Transactions_id  User_id  Products  Ratings
0           200000     1711      6327        3
1           200001     1132     22043        2
2           200002     1900     55071        0
3           200003     1548     32236        5
4           200004     1273     24053        3

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Transactions_id  100000 non-null  int64
 1   User_id          100000 non-null  int64
 2   Products         100000 non-null  int64
 3   Ratings          100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

In [89]:
df.groupby('User_id').count()['Ratings'].sort_values(ascending=False)

User_id
1774    136
1558    131
1213    129
1818    129
1380    128
       ...
1090     77
1276     76
1838     73
1125     73
1719     71
Name: Ratings, Length: 1000, dtype: int64

In [90]:
df=df[df['Ratings']>=4].sort_values('Ratings')
df

       Transactions_id  User_id  Products  Ratings
50178           250178     1185     53278        4
55917           255917     1607      7524        4
55916           255916     1285      4134        4
55906           255906     1701     28108        4
55902           255902     1089     36984        4
...                ...      ...       ...      ...
20895           220895     1106     29168        5
58722           258722     1011     47298        5
58721           258721     1984     24707        5
20901           220901     1893     50005        5
3               200003     1548     32236        5

[33345 rows x 4 columns]

In [91]:
x=df.groupby('Products').count()['Ratings']==1
x[x]

Products
1164     True
1165     True
1529     True
1533     True
1536     True
         ...
59978    True
59983    True
59986    True
59989    True
59990    True
Name: Ratings, Length: 15825, dtype: bool

In [92]:
new_df=df.pivot_table(index='Products',columns='User_id',values='Ratings')
new_df.fillna(0,inplace=True)
new_df = new_df.astype(int)
new_df

User_id,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
Products,,,,,,,,,,,,,,,,,,,,,
1163,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1164,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1165,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1529,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1533,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59983,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59986,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59988,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59989,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59990,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [93]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23502 entries, 1163 to 59990
Columns: 1000 entries, 1000 to 1999
dtypes: int32(1000)
memory usage: 89.8 MB

In [94]:
new_df = new_df.astype('int8')
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23502 entries, 1163 to 59990
Columns: 1000 entries, 1000 to 1999
dtypes: int8(1000)
memory usage: 22.6 MB

In [95]:
new_df.to_csv('pivot_table_transactions.csv',header=True, index=True)
print('File Saved')

File Saved

In [96]:
df=pd.read_csv('pivot_table_transactions.csv')
df

,Products,1000,1001,1002,1003,1004,1005,1006,1007,1008,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,1163,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1164,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1165,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1529,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1533,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23497,59983,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23498,59986,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23499,59988,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23500,59989,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23501,59990,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [98]:
df

,Products,1000,1001,1002,1003,1004,1005,1006,1007,1008,...,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999
0,1163,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1164,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1165,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1529,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1533,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23497,59983,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23498,59986,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23499,59988,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23500,59989,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23501,59990,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0